### ISSUE TITLE
Odd-numbered lists crash on currentmatchup

### ISSUE THREAD

**Issue by Karlkorv** [Karlkorv/best-song#45]
When trying to get the currentmatchup with only one contender, the program crashes

Fix this by organizing a new top level and automatically giving the remaining entry the w

**Comment by Karlkorv** [comment]
Kraschar också här:
```
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Index was outside the bounds of the array.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at best_song.Pages.Tournament.BuildRenderTree(RenderTreeBuilder __builder) in C:\Users\Janne\RiderProjects\best-song\src\Pages\Tournament.razor:line 29
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'LnzMSjEq1LsbSKB80ctrCh2-QyqZrWWiJ-b1retaZrA'.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at best_song.Pages.Tournament.BuildRenderTree(RenderTreeBuilder __builder) in C:\Users\Janne\RiderProjects\best-song\src\Pages\Tournament.razor:line 29
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```
